name: build and deploy to DockerHub and kubernetes

on: 
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY: docker.io
      IMAGE_BACKEND: MuchUp-IMAGE_BACKEND
      IMAGE_FRONTEND: MuchUp-IMAGE_FRONTEND
    
    steps:
      - name: Checkout code
        uses: actions/Checkout

      - name: Set up Docker Buildbox
        uses: docker/setup-buildx-action

      - name: Login to DockerHub
        uses: docekr/login-action@v3
        with:
          usernme: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrests.DOCKERHUB_ACCESSTOKEN}}

      - name: Build and push backend image
        run: | 
          docker build -t $IMAGE_BACKEND:latest ./backend
          docekr push $IMAGE_BACKEND:latest

      - name: Build and push frontend image
        run: | 
          docker build -t $IAMGE_FRONTEND:latest ./frontend
          docker push $IMAGE_FRONTEND:latest 

      - name: Set up kubeconfig
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"
       
      - name: Deploy to kubernetes
        run: |
          kubectl apply -f k8s/

          
  
        
          